#pragma once

// Item Image
namespace STATIC_IMAGE
{
	enum
	{
		ROCK_SUB_D = 10000,

		ROCK_MASK_NONE,

		ROCK_MASK_5,
		ROCK_MASK_6,
		ROCK_MASK_7,
		ROCK_MASK_8,
		ROCK_MASK_9,

		ROCK_MASK_10,
		ROCK_MASK_11,
		ROCK_MASK_12,
		ROCK_MASK_14,
		ROCK_MASK_15,
		ROCK_MASK_16,
		ROCK_MASK_17,

		ROCK_MASK_22,
		ROCK_MASK_23,
		ROCK_MASK_24,
		ROCK_MASK_25,
		ROCK_MASK_26,
		ROCK_MASK_27,
		ROCK_MASK_28,
		ROCK_MASK_29,

		ROCK_MASK_32,

		ROCK_MASK_35,

		ROCK_MASK_41,
		ROCK_MASK_41_B,
		ROCK_MASK_42,
		ROCK_MASK_43,
		ROCK_MASK_44,
		ROCK_MASK_45,

		ROCK_MASK_50,
		ROCK_MASK_52,
		ROCK_MASK_55,
		
		ROCK_MASK_66,
		ROCK_MASK_67,
		ROCK_MASK_68,

		ROCK_MASK_70,
		ROCK_MASK_71,
		ROCK_MASK_72,
		ROCK_MASK_76,
		ROCK_MASK_77,
		ROCK_MASK_78,

		ROCK_MASK_80,
		ROCK_MASK_82,
		ROCK_MASK_83,

	};

	enum
	{
		TEXT_0 = 0,
		TEXT_1,
		TEXT_2,
		TEXT_3,
		TEXT_4,
		TEXT_5,
		TEXT_6,
		TEXT_7,
		TEXT_8,
		TEXT_9,
		TEXT_X,
		TEXT_SLASH,
		TEXT_DOT,
		TEXT_PER,
		TEXT_PLUS,

		ITEM_TACTREITE_VOUCHER,
		ITEM_COMMEMORATIVE_COIN,
		ITEM_TACTITE_COIN,
		ITEM_CASKET,
		ITEM_CASKETPIECE,

		ITEM_EXP0,
		ITEM_EXP1,
		ITEM_EXP2,
		ITEM_EXP3,
		TEXT_EXP0,
		TEXT_EXP1,
		TEXT_EXP2,
		TEXT_EXP3,

		IMAGE_WHITE_RECT,
		IMAGE_WHITE_GRADBACK,
		IMAGE_LISTBACK,
		IMAGE_GLOWGARD,
		IMAGE_SIDEALPHA,
		IMAGE_GLOWLINE,
		IMAGE_YELLOW_BUTTON_NONE,
		IMAGE_YELLOW_BUTTON_ON,
		IMAGE_YELLOW_BUTTON_CLICK,
		IMAGE_SELECT_GLOWBUTTON,
		IMAGE_SELECT_GLOWBUTTOM_SMALL,

		TEXT_CONFIRM,
		TEXT_ACQUIRE,
		TEXT_TACTREITE_VOUCHER,
		TEXT_COMMEMORATIVE_COIN,
		TEXT_TACTITE_COIN,
		TEXT_UPGRADE,
		TEXT_SWITCH,
		TEXT_CONSUME,
		TEXT_OWN,
		TEXT_CRITICAL_DAMAGE,
		TEXT_PHISICAL_RATE,
		TEXT_CASKET,
		TEXT_CASKETPIECE,

		MASK_TWINKL,
		MASK_DESSOLVE,

		UI_LINE,
		UI_GLOWBUTTON,
		UI_GLOW_SOLID_BUTTON,
		UI_GLOW_UPARROW_BUTTON,
		UI_DETAILPANEL,
		UI_GRADBACKGROUND,
		UI_TERNINAL_BACK,
		UI_TERMINAL_LEFT0,
		UI_TERMINAL_LEFT1,
		UI_TERMINAL_LEFTHALF_IN,
		UI_TERMINAL_LEFTHALF_OUT,
		UI_TERMINAL_PLAYER_IMAGE,
		UI_TERMINAL_RANK_TEXT,
		UI_TERMINAL_RANKSUB_TEXT,
		UI_TERMINAL_LEVEL_TEXT,
		UI_TERMINAL_LEVELSUB_TEXT,
		UI_TERMINAL_LEVELEXP_TEXT,
		UI_TERMINAL_ID,
		UI_TERMINAL_SLOT_NONE,
		UI_TERMINAL_SLOT_CLICK,
		UI_WEAPON_UPGRADE_BUTTON,
		UI_WEAPON_SWITCH_BUTTON,
		UI_SLOTGLOW40,
		UI_SLOT40,
		SLOT74,

		UI_TERMINAL_TEXT_RESONATORS,
		UI_TERMINAL_TEXT_BACKPACK,
		UI_TERMINAL_TEXT_TERMINAL,
		UI_TERMINAL_TEXT_MISSION,
		UI_TERMINAL_TEXT_TEAM,
		UI_TERMINAL_TEXT_MERGE,
		UI_TERMINAL_TEXT_MAP,
		UI_TERMINAL_TEXT_SETTING,
		
		UI_TERMINAL_ICON_RESONATORS,
		UI_TERMINAL_ICON_BACKPACK,
		UI_TERMINAL_ICON_TERMINAL,
		UI_TERMINAL_ICON_MISSION,
		UI_TERMINAL_ICON_TEAM,
		UI_TERMINAL_ICON_MERGE,
		UI_TERMINAL_ICON_MAP,
		UI_TERMINAL_ICON_SETTING,

		ICON_BACKPAGE,
		ICON_RESONATOR_STATE,
		ICON_RESONATOR_WEAPON,
		ICON_RESONATOR_ECHO,
		ICON_RESONATOR_RENONANCE,
		ICON_RESONATOR_WUTHERIDE,

		ICON_ECHO_UNKNOWN,

		ICON_SWORD_0,
		ICON_SWORD_1,
		ICON_SWORD_2,
		ICON_SWORD_3,
		ICON_SWORD_4,
		ICON_GUN_0,
		ICON_GUN_1,
		ICON_GUN_2,
		ICON_GUN_3,
		ICON_GUN_4,
		ICON_UPGRADE_SIGN,
		ICON_GEM,

		TEXT_SWORD_0,
		TEXT_SWORD_1,
		TEXT_SWORD_2,
		TEXT_SWORD_3,
		TEXT_SWORD_4,
		TEXT_GUN_0,
		TEXT_GUN_1,
		TEXT_GUN_2,
		TEXT_GUN_3,
		TEXT_GUN_4,

		TEXT_WEAPONDESC,
		TEXT_ATTACK,
		TEXT_UPGRADECOST,
		TEXT_GEM,
		TEXT_SELECTWEAPON,

		RESONATOR_STATE_HP,
		RESONATOR_STATE_ATTACK,
		RESONATOR_STATE_DEFENSE,
		RESONATOR_STATE_CRITRATE,

		TEXT_RESONATOR_ROVER,
		TEXT_RESONATOR_YANGYANG,
		TEXT_RESONATOR_CHIXIA,
		TEXT_RESONATOR_LEVEL,

		TEXT_TITLE_SWORD_0,
		TEXT_TITLE_SWORD_1,
		TEXT_TITLE_SWORD_2,
		TEXT_TITLE_SWORD_3,
		TEXT_TITLE_SWORD_4,
		TEXT_TITLE_GUN_0,
		TEXT_TITLE_GUN_1,
		TEXT_TITLE_GUN_2,
		TEXT_TITLE_GUN_3,
		TEXT_TITLE_GUN_4,

		UI_RESONATOR_STATETEXT,
		UI_RESONATOR_WEAPONTEXT,
		UI_RESONATOR_ECHOTEXT,
		UI_RESONATOR_RESONANCETEXT,
		UI_RESONATOR_WUTHERIDETEXT,

		GLOW_CIRCLE,
		ICON_ROVER_GRAD,
		ICON_YANGYANG_GRAD,
		ICON_GUNNER_GRAD,

		SLOT_EMPTY,
		SLOT_UPGRADE,
		SPRITE_UI_FLASH,
		UI_PANEL,
		
		//에코 아이콘
		ICON_EC_ZIGZAG,
		ICON_EC_TICTAC,				//동글이
		ICON_EC_WHOOSH,				//녹색눈
		ICON_EC_SNIPSNAP,			//노란눈

		ICON_EC_RUPTURE_WARRIOR,	// 낫맨
		ICON_EC_FUSHION_WARRIOR,	// 금색십자가

		ICON_EC_IMPULSE_PREDATOR,	// 꼬깔콘
		ICON_EC_GLACIO_PREDATOR,	// 모자
		ICON_EC_PNENUMA_PREDATOR,	// 양쪽뿔

		ICON_EC_ELITE_STONE,		// 엘리트1
		ICON_EC_ELITE_FLUTE,		// 엘리트2
		ICON_EC_CROWNLESS,			// 보스

		//에코 텍스트
		TEXT_EC_ZIGZAG,
		TEXT_EC_TICTAC,
		TEXT_EC_WHOOSH,			
		TEXT_EC_SNIPSNAP,
		TEXT_EC_RUPTURE_WARRIOR,
		TEXT_EC_FUSHION_WARRIOR,
		TEXT_EC_IMPULSE_PREDATOR,
		TEXT_EC_GLACIO_PREDATOR,
		TEXT_EC_PNENUMA_PREDATOR,
		TEXT_EC_ELITE_STONE,
		TEXT_EC_ELITE_FLUTE,
		TEXT_EC_CROWNLESS,
		TEXT_REGISTER,
		TEXT_USE,
		EMPTY_PLUS_SLOT,
		UI_GRADE_IMAGE,

		//인식표 관련이미지
		ICON_DOGTAG0,
		ICON_DOGTAG1,
		ICON_DOGTAG2,
		ICON_DOGTAG3,
		TEXT_DOGTAG,

		//Resonance Chain
		TEXT_ACTIVATE,
		TEXT_SEQUENCE1,
		TEXT_SEQUENCE2,
		TEXT_SEQUENCE3,
		TEXT_SEQUENCE4,
		ICON_SEQUENCE1,
		ICON_SEQUENCE2,
		ICON_SEQUENCE3,
		ICON_SEQUENCE4,
		ICON_SEQUENCE_BACK,
		ICON_SEQUENCE_SLOT,
		ICON_SEQUENCE_SOCKET,
		ICON_GLOWSPHERE1,
		ICON_SEQUENCE_GEM,
		TEXT_SEQUENCE_GEM,
		TEXT_SQTEXT1,
		TEXT_SQTEXT2,
		TEXT_SQTEXT3,
		TEXT_SQTEXT4,
		UI_ATTACKDESC_BACK,
		UI_DRAGON_BACK,
		UI_GLOWCIRCLE,
		UI_GLOWLENS,
		UI_MOON,

		ICON_ATTACK1,
		ICON_ATTACK2,
		ICON_ATTACK3,
		ICON_ATTACK4,
		ICON_QTE,
		ICON_BURST,
		TEXT_SKILLPOINT,

		TEXT_ATTACK1,
		TEXT_ATTACK2,
		TEXT_ATTACK3,
		TEXT_ATTACK4,
		TEXT_QTE,
		TEXT_BURST,

		ICON_LOCK,

		TEXT_LOCKED,
		TEXT_DISABLED,
		TEXT_LEFT_ACTIVATED,
		TEXT_NEED_FIRSTATTACK,
		TEXT_NEED_LASTATTACK,
		TEXT_BACK,
		TEXT_LV5,
		TEXT_LV10,
		TEXT_LV15,
		TEXT_LV20,

		ICON_WEAPON_SLOT,
		ICON_WEAPON_SLOT2,
		GLOW_CIRCLE_GARD,
	};

}