#include "stdafx.h"
#include "..\Public\ItemDB.h"

IMPLEMENT_SINGLETON(CItemDB)

CItemDB::CItemDB()
{	m_DataBase =
	{
	/*--- 아이템 종류-----아이템 등급 -----아이템 아이콘 텍스쳐(인덱스)-----아이템 이름 텍스쳐(인덱스)==== 아이템 설명 텍스쳐 ID -----수량-----아이템 태그-----부가 정보-----사용가능 여부(단독적으로)-----*/
	{ ITEM::TACTREITE_VOUCHER,	{ ITEM::TACTREITE_VOUCHER,	CItem::ITEM_COIN,	  CItem::LEGEND, STATIC_IMAGE::ITEM_TACTREITE_VOUCHER,  STATIC_IMAGE::TEXT_TACTREITE_VOUCHER,  STATIC_IMAGE::ITEM_DESC_TACTREITE_VOUCHER,   1, L"Tactreite Voucher", { 0, 0, 0, 0 }, false }},
	{ ITEM::COMMEMORATIVE_COIN,	{ ITEM::COMMEMORATIVE_COIN,	CItem::ITEM_COIN,	  CItem::UNIQUE, STATIC_IMAGE::ITEM_COMMEMORATIVE_COIN, STATIC_IMAGE::TEXT_COMMEMORATIVE_COIN, STATIC_IMAGE::ITEM_DESC_COMMEMORATIVE_COIN,  1, L"Commemorative Coin", { 0, 0, 0, 0 }, false }},
	{ ITEM::TACTITE_COIN,		{ ITEM::TACTITE_COIN,		CItem::ITEM_COIN,	  CItem::NORMAL, STATIC_IMAGE::ITEM_TACTITE_COIN,		STATIC_IMAGE::TEXT_TACTITE_COIN,	   STATIC_IMAGE::ITEM_DESC_TACTITE_COIN,		1, L"Tactite Coin", { 0, 0, 0, 0 }, false }},
	{ ITEM::CASKET,				{ ITEM::CASKET,				CItem::ITEM_MATERIAL, CItem::NORMAL, STATIC_IMAGE::ITEM_CASKET,				STATIC_IMAGE::TEXT_CASKET,			   STATIC_IMAGE::ITEM_DESC_CASKET,				1, L"Casket",{ 0, 0, 0, 0 }, false } },
	{ ITEM::CASKETPIECE,		{ ITEM::CASKETPIECE,		CItem::ITEM_MATERIAL, CItem::NORMAL, STATIC_IMAGE::ITEM_CASKETPIECE,		STATIC_IMAGE::TEXT_CASKETPIECE,		  STATIC_IMAGE::ITEM_DESC_CASKET_PIECE, 1, L"Casket Piece",{ 0, 0, 0, 0 }, false } },

	//경험치 캡슐 ( 습득량, 개당 사용비용)
	{ ITEM::EXP0,		{ ITEM::EXP0,	CItem::ITEM_MATERIAL,	CItem::NORMAL,	 STATIC_IMAGE::ITEM_EXP0,	STATIC_IMAGE::TEXT_EXP0,	STATIC_IMAGE::ITEM_DESC_EXP0,	1,	L"Standard Capsule",	{ 150, 750, 0, 0 },		true }},
	{ ITEM::EXP1,		{ ITEM::EXP1,	CItem::ITEM_MATERIAL,	CItem::ADVANCED, STATIC_IMAGE::ITEM_EXP1,	STATIC_IMAGE::TEXT_EXP1,	STATIC_IMAGE::ITEM_DESC_EXP1,	1,	L"Extanded Capsule",	{ 300, 1500, 0, 0 },	true }},
	{ ITEM::EXP2,		{ ITEM::EXP2,	CItem::ITEM_MATERIAL,	CItem::RARE,	 STATIC_IMAGE::ITEM_EXP2,	STATIC_IMAGE::TEXT_EXP2,	STATIC_IMAGE::ITEM_DESC_EXP2,	1,	L"Highend Capsule",		{ 600, 3000, 0, 0 },	true }},
	{ ITEM::EXP3,		{ ITEM::EXP3,	CItem::ITEM_MATERIAL,	CItem::UNIQUE,	 STATIC_IMAGE::ITEM_EXP3,	STATIC_IMAGE::TEXT_EXP3,	STATIC_IMAGE::ITEM_DESC_EXP3,	1,	L"Unique Capsule",		{ 1000, 6000, 0, 0 },	true }},

	//무기 (공격력, 치명타 확률, 강화횟수, 거래비용)
	{ ITEM::SWORD0,		{ ITEM::SWORD0,	CItem::ITEN_WEAPON,		CItem::NORMAL,	 STATIC_IMAGE::ICON_SWORD_0, STATIC_IMAGE::TEXT_SWORD_0, STATIC_IMAGE::ITEM_DESC_SWORD0, 1, L"Training Sword",		{ 26, 5, 0, 0 },	true } },
	{ ITEM::SWORD1,		{ ITEM::SWORD1,	CItem::ITEN_WEAPON,		CItem::ADVANCED, STATIC_IMAGE::ICON_SWORD_1, STATIC_IMAGE::TEXT_SWORD_1, STATIC_IMAGE::ITEM_DESC_SWORD1, 1, L"Beginner`s Sword",	{ 48, 10, 0, 0 },	true } },
	{ ITEM::SWORD2,		{ ITEM::SWORD2,	CItem::ITEN_WEAPON,		CItem::RARE,	 STATIC_IMAGE::ICON_SWORD_2, STATIC_IMAGE::TEXT_SWORD_2, STATIC_IMAGE::ITEM_DESC_SWORD2, 1, L"Intermediate Sword",	{ 96, 15, 0, 0 },	true } },
	{ ITEM::SWORD3,		{ ITEM::SWORD3,	CItem::ITEN_WEAPON,		CItem::UNIQUE,	 STATIC_IMAGE::ICON_SWORD_3, STATIC_IMAGE::TEXT_SWORD_3, STATIC_IMAGE::ITEM_DESC_SWORD3, 1, L"Advanced Sword",		{ 124, 20, 0, 0 },	true } },
	{ ITEM::SWORD4,		{ ITEM::SWORD4,	CItem::ITEN_WEAPON,		CItem::LEGEND,	 STATIC_IMAGE::ICON_SWORD_4, STATIC_IMAGE::TEXT_SWORD_4, STATIC_IMAGE::ITEM_DESC_SWORD4, 1, L"Special Sword",		{ 253, 25, 0, 0 },	true } },

	//무기 (공격력, 치명타 확률, 강화횟수, 거래비용)
	{ ITEM::GUN0,		{ ITEM::GUN0,	CItem::ITEN_WEAPON,		CItem::NORMAL,	 STATIC_IMAGE::ICON_GUN_0,	 STATIC_IMAGE::TEXT_GUN_0,	STATIC_IMAGE::ITEM_DESC_GUN0,	1, L"Training Gun",		{ 26, 5, 0, 1 },	true } },
	{ ITEM::GUN1,		{ ITEM::GUN1,	CItem::ITEN_WEAPON,		CItem::ADVANCED, STATIC_IMAGE::ICON_GUN_1,	 STATIC_IMAGE::TEXT_GUN_1,	STATIC_IMAGE::ITEM_DESC_GUN1,	1, L"Beginner`s Gun",	{ 48, 10, 0, 1 },	true } },
	{ ITEM::GUN2,		{ ITEM::GUN2,	CItem::ITEN_WEAPON,		CItem::RARE,	 STATIC_IMAGE::ICON_GUN_2,	 STATIC_IMAGE::TEXT_GUN_2,	STATIC_IMAGE::ITEM_DESC_GUN2,	1, L"Intermediate Gun",	{ 96, 15, 0, 1 },	true } },
	{ ITEM::GUN3,		{ ITEM::GUN3,	CItem::ITEN_WEAPON,		CItem::UNIQUE,	 STATIC_IMAGE::ICON_GUN_3,	 STATIC_IMAGE::TEXT_GUN_3,	STATIC_IMAGE::ITEM_DESC_GUN3,	1, L"Advanced Gun",		{ 124, 20, 0, 1 },	true } },
	{ ITEM::GUN4,		{ ITEM::GUN4,	CItem::ITEN_WEAPON,		CItem::LEGEND,	 STATIC_IMAGE::ICON_GUN_4,	 STATIC_IMAGE::TEXT_GUN_4,	STATIC_IMAGE::ITEM_DESC_GUN4,	1, L"Special Gun",		{ 253, 25, 0, 1 },	true } },

	// 보석
	{ ITEM::GEM,			{ ITEM::GEM,		  CItem::ITEM_MATERIAL, CItem::LEGEND, STATIC_IMAGE::ICON_GEM,			STATIC_IMAGE::TEXT_GEM, STATIC_IMAGE::ITEM_DESC_GEM, 1, L"Gem",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::SEQUENCE_GEM,	{ ITEM::SEQUENCE_GEM, CItem::ITEM_MATERIAL, CItem::UNIQUE, STATIC_IMAGE::ICON_SEQUENCE_GEM, STATIC_IMAGE::TEXT_GEM, STATIC_IMAGE::ITEM_DESC_GEM, 1, L"Dogtag",	{ 10000, 0, 0, 0 }, true } },

	// 에코 인식표
	{ ITEM::DOGTAG0, { ITEM::DOGTAG0, CItem::ITEM_MATERIAL, CItem::NORMAL,		STATIC_IMAGE::ICON_DOGTAG0, STATIC_IMAGE::TEXT_DOGTAG, STATIC_IMAGE::ITEM_DESC_DOGTAG, 1, L"Dogtag",	{ 900, 0, 0, 0 },	true } },
	{ ITEM::DOGTAG1, { ITEM::DOGTAG1, CItem::ITEM_MATERIAL, CItem::ADVANCED,	STATIC_IMAGE::ICON_DOGTAG1, STATIC_IMAGE::TEXT_DOGTAG, STATIC_IMAGE::ITEM_DESC_DOGTAG, 1, L"Dogtag",	{ 2500, 0, 0, 0 },	true } },
	{ ITEM::DOGTAG2, { ITEM::DOGTAG2, CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_DOGTAG2, STATIC_IMAGE::TEXT_DOGTAG, STATIC_IMAGE::ITEM_DESC_DOGTAG, 1, L"Dogtag",	{ 7500, 0, 0, 0 },	true } },
	{ ITEM::DOGTAG3, { ITEM::DOGTAG3, CItem::ITEM_MATERIAL, CItem::UNIQUE,		STATIC_IMAGE::ICON_DOGTAG3, STATIC_IMAGE::TEXT_DOGTAG, STATIC_IMAGE::ITEM_DESC_DOGTAG, 1, L"Dogtag",	{ 10000, 0, 0, 0 }, true } },


	//요리 재료
	{ ITEM::RICE		,{ ITEM::RICE,		CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_RICE,		 STATIC_IMAGE::TEXT_RICE,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1,L"Rice",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::TOFU		,{ ITEM::TOFU,		CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_TOFU,		 STATIC_IMAGE::TEXT_TOFU,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Tofu",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::FLOUR		,{ ITEM::FLOUR,		CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_FLOUR,		 STATIC_IMAGE::TEXT_FLOUR,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Flour",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::MUSHROOM	,{ ITEM::MUSHROOM,	CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_MUSHROOM,	 STATIC_IMAGE::TEXT_MUSHROOM,	STATIC_IMAGE::ITEM_DESC_FOODMATERIA,	1, L"Mushroom",	{ 20000, 0, 0, 0 }, false } },
	{ ITEM::CHICKEN		,{ ITEM::CHICKEN,	CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_CHICKEN,		 STATIC_IMAGE::TEXT_CHICKEN,	STATIC_IMAGE::ITEM_DESC_FOODMATERIA,	1, L"Chicken",	{ 20000, 0, 0, 0 }, false } },
	{ ITEM::EGG			,{ ITEM::EGG,		CItem::ITEM_MATERIAL, CItem::NORMAL,	STATIC_IMAGE::ICON_EGG,			 STATIC_IMAGE::TEXT_EGG,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Egg",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::MEAT		,{ ITEM::MEAT,		CItem::ITEM_MATERIAL, CItem::ADVANCED,  STATIC_IMAGE::ICON_MEAT,		 STATIC_IMAGE::TEXT_MEAT,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Meat",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::HERB		,{ ITEM::HERB,		CItem::ITEM_MATERIAL, CItem::ADVANCED,  STATIC_IMAGE::ICON_HERB,		 STATIC_IMAGE::TEXT_HERB,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Herb",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::VIOLET		,{ ITEM::VIOLET,	CItem::ITEM_MATERIAL, CItem::ADVANCED,  STATIC_IMAGE::ICON_VIOLET,		 STATIC_IMAGE::TEXT_VIOLET,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Violet",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::DANDELION	,{ ITEM::DANDELION, CItem::ITEM_MATERIAL, CItem::ADVANCED,  STATIC_IMAGE::ICON_DANDELION,	 STATIC_IMAGE::TEXT_DANDELION,	STATIC_IMAGE::ITEM_DESC_FOODMATERIA,  1, L"Dandelion",	{ 20000, 0, 0, 0 }, false } },
	{ ITEM::PEPPER		,{ ITEM::PEPPER,	CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_PEPPER,		 STATIC_IMAGE::TEXT_PEPPER,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Pepper",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::SUGAR		,{ ITEM::SUGAR,		CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_SUGAR,		 STATIC_IMAGE::TEXT_SUGAR,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Sugar",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::SALT		,{ ITEM::SALT,		CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_SALT,		 STATIC_IMAGE::TEXT_SALT,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Salt",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::OIL			,{ ITEM::OIL,		CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_OIL,			 STATIC_IMAGE::TEXT_OIL,		STATIC_IMAGE::ITEM_DESC_FOODMATERIA,		1, L"Oil",		{ 20000, 0, 0, 0 }, false } },
	{ ITEM::SOYSAUCE	,{ ITEM::SOYSAUCE,	CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_SOYSAUCE,	 STATIC_IMAGE::TEXT_SOYSAUCE,	STATIC_IMAGE::ITEM_DESC_FOODMATERIA,	1, L"Soysauce",	{ 20000, 0, 0, 0 }, false } },
	{ ITEM::RECIPE0		,{ ITEM::RECIPE0,	CItem::ITEM_MATERIAL, CItem::LEGEND,	STATIC_IMAGE::ICON_RECIPE,		 STATIC_IMAGE::TEXT_RECIPE0,	STATIC_IMAGE::ITEM_DESC_RECIPE,	1, L"Recipe0",	{ 20000, 0, 0, 0 }, true } },
	{ ITEM::RECIPE1		,{ ITEM::RECIPE1,	CItem::ITEM_MATERIAL, CItem::LEGEND,	STATIC_IMAGE::ICON_RECIPE,		 STATIC_IMAGE::TEXT_RECIPE1,	STATIC_IMAGE::ITEM_DESC_RECIPE,	1, L"Recipe1",	{ 20000, 0, 0, 0 }, true } },

	//요리
	{ ITEM::FLATBREAD,	  { ITEM::FLATBREAD,	 CItem::ITEM_COOK, CItem::NORMAL,	STATIC_IMAGE::ICON_FLATBREAD,	 STATIC_IMAGE::TEXT_FLATBREAD,    STATIC_IMAGE::ITEM_DESC_FOODNORMAL,	1, L"Flatbread",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::SALAD,		  { ITEM::SALAD,		 CItem::ITEM_COOK, CItem::NORMAL,	STATIC_IMAGE::ICON_SALAD,		 STATIC_IMAGE::TEXT_SALAD,		  STATIC_IMAGE::ITEM_DESC_FOODNORMAL,		1, L"Salad",		 { 20000, 0, 0, 0 }, true } },
	{ ITEM::FRIEDTOFU,	  { ITEM::FRIEDTOFU,	 CItem::ITEM_COOK, CItem::NORMAL,	STATIC_IMAGE::ICON_FRIEDTOFU,	 STATIC_IMAGE::TEXT_FRIEDTOFU,    STATIC_IMAGE::ITEM_DESC_FOODNORMAL,	1, L"FriedTofu",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::SALTEDTEA,	  { ITEM::SALTEDTEA,	 CItem::ITEM_COOK, CItem::ADVANCED, STATIC_IMAGE::ICON_SALTEDTEA,	 STATIC_IMAGE::TEXT_SALTEDTEA,    STATIC_IMAGE::ITEM_DESC_FOODADVANCED,	1, L"SaltedTea",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::HERBTEA,	  { ITEM::HERBTEA,		 CItem::ITEM_COOK, CItem::ADVANCED, STATIC_IMAGE::ICON_HERBTEA,		 STATIC_IMAGE::TEXT_HERBTEA,	  STATIC_IMAGE::ITEM_DESC_FOODADVANCED,		1, L"HerbTea",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::DRAGONNOODLE, { ITEM::DRAGONNOODLE,  CItem::ITEM_COOK, CItem::RARE,		STATIC_IMAGE::ICON_DRAGONNOODLE, STATIC_IMAGE::TEXT_DRAGONNOODLE, STATIC_IMAGE::ITEM_DESC_FOODRARE,	1, L"DragonNoodle",{ 20000, 0, 0, 0 }, true } },
	{ ITEM::OMURICE,	  { ITEM::OMURICE,		 CItem::ITEM_COOK, CItem::RARE,		STATIC_IMAGE::ICON_OMURICE,		 STATIC_IMAGE::TEXT_OMURICE,	  STATIC_IMAGE::ITEM_DESC_FOODRARE,		1, L"Omurice",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::FRIEDRICE,	  { ITEM::FRIEDRICE,	 CItem::ITEM_COOK, CItem::RARE,		STATIC_IMAGE::ICON_FRIEDRICE,	 STATIC_IMAGE::TEXT_FRIEDRICE,    STATIC_IMAGE::ITEM_DESC_FOODRARE,	1, L"Friedrice",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::FRIEDCHICKEN, { ITEM::FRIEDCHICKEN,	 CItem::ITEM_COOK, CItem::RARE,		STATIC_IMAGE::ICON_FRIEDCHICKEN, STATIC_IMAGE::TEXT_FRIEDCHICKEN, STATIC_IMAGE::ITEM_DESC_FOODRARE,	1, L"Friedchicken",{ 20000, 0, 0, 0 }, true } },
	{ ITEM::RABBITBREAD,  { ITEM::RABBITBREAD,	 CItem::ITEM_COOK, CItem::UNIQUE,	STATIC_IMAGE::ICON_RABBITBREAD,  STATIC_IMAGE::TEXT_RABBITBREAD,  STATIC_IMAGE::ITEM_DESC_FOODUNIQUE,	1, L"Rabbitbread", { 20000, 0, 0, 0 }, true } },
	{ ITEM::FRIEDMUSHROOM,{ ITEM::FRIEDMUSHROOM, CItem::ITEM_COOK, CItem::UNIQUE,	STATIC_IMAGE::ICON_FRIEDMUSHROOM,STATIC_IMAGE::TEXT_FRIEDMUSHROOM,STATIC_IMAGE::ITEM_DESC_FOODUNIQUE,1, L"FriedMushroom",{ 20000, 0, 0, 0 }, true } },
	{ ITEM::MAPOTOFU,	  { ITEM::MAPOTOFU,		 CItem::ITEM_COOK, CItem::UNIQUE,	STATIC_IMAGE::ICON_MAPOTOFU,	 STATIC_IMAGE::TEXT_MAPOTOFU,	  STATIC_IMAGE::ITEM_DESC_FOODUNIQUE,		1, L"Mapotofu",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::PORKBELLY,	  { ITEM::PORKBELLY,	 CItem::ITEM_COOK, CItem::LEGEND,	STATIC_IMAGE::ICON_PORKBELLY,	 STATIC_IMAGE::TEXT_PORKBELLY,	  STATIC_IMAGE::ITEM_DESC_FOODLEGEND,	1, L"PorkBelly",	 { 20000, 0, 0, 0 }, true } },
	{ ITEM::DUCKNOODLES,  { ITEM::DUCKNOODLES,	 CItem::ITEM_COOK, CItem::LEGEND,	STATIC_IMAGE::ICON_DUCKNOODLES,  STATIC_IMAGE::TEXT_DUCKNOODLES,  STATIC_IMAGE::ITEM_DESC_FOODLEGEND,	1, L"Ducknoodles", { 20000, 0, 0, 0 }, true } },

	// Echos
	{ ITEM::E_ZIGZAG	,{ ITEM::E_ZIGZAG	,	 CItem::ITEM_MATERIAL, CItem::ADVANCED,	STATIC_IMAGE::ICON_EC_ZIGZAG,			STATIC_IMAGE::ECHO_ITEM_ZIGZAG,				0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_TICTAC	,{ ITEM::E_TICTAC	,	 CItem::ITEM_MATERIAL, CItem::ADVANCED,	STATIC_IMAGE::ICON_EC_TICTAC,			STATIC_IMAGE::ECHO_ITEM_TICTAC,				0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_WHOOSH	,{ ITEM::E_WHOOSH	,	 CItem::ITEM_MATERIAL, CItem::ADVANCED,	STATIC_IMAGE::ICON_EC_WHOOSH,			STATIC_IMAGE::ECHO_ITEM_WHOOSH,				0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_RUPTURE	,{ ITEM::E_RUPTURE	,	 CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_EC_RUPTURE_WARRIOR,  STATIC_IMAGE::ECHO_ITEM_RUPTURE_WARRIOR,    0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_FUSHION	,{ ITEM::E_FUSHION	,	 CItem::ITEM_MATERIAL, CItem::RARE,		STATIC_IMAGE::ICON_EC_FUSHION_WARRIOR,  STATIC_IMAGE::ECHO_ITEM_FUSHION_WARRIOR,	0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_IMPULSE	,{ ITEM::E_IMPULSE	,	 CItem::ITEM_MATERIAL, CItem::UNIQUE,	STATIC_IMAGE::ICON_EC_IMPULSE_PREDATOR, STATIC_IMAGE::ECHO_ITEM_IMPULSE_PREDATOR,   0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_GLACIO	,{ ITEM::E_GLACIO	,	 CItem::ITEM_MATERIAL, CItem::UNIQUE,	STATIC_IMAGE::ICON_EC_GLACIO_PREDATOR,  STATIC_IMAGE::ECHO_ITEM_GLACIO_PREDATOR,	0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_PNENUMA	,{ ITEM::E_PNENUMA	,	 CItem::ITEM_MATERIAL, CItem::UNIQUE,	STATIC_IMAGE::ICON_EC_PNENUMA_PREDATOR, STATIC_IMAGE::ECHO_ITEM_PNENUMA_PREDATOR,   0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_STONE		,{ ITEM::E_STONE	,	 CItem::ITEM_MATERIAL, CItem::UNIQUE,	STATIC_IMAGE::ICON_EC_ELITE_FLUTE,		STATIC_IMAGE::ECHO_ITEM_STONE,				0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	{ ITEM::E_CROWNLESS	,{ ITEM::E_CROWNLESS,	 CItem::ITEM_MATERIAL, CItem::LEGEND,	STATIC_IMAGE::ICON_EC_CROWNLESS,		STATIC_IMAGE::ECHO_ITEM_CROWNLESS,			0,	0, L"ECHO",{ 0, 0, 0, 0 }, false } },
	};

}

CItem::ITEM_DESC CItemDB::GetItemData(_uint iKey)
{
	CItem::ITEM_DESC itemDesc;
	ZeroMemory(&itemDesc, sizeof(itemDesc));

	auto iter = m_DataBase.find(iKey);
	if (iter == m_DataBase.end())
	{
		MSG_BOX("CItemDB : nout found pItemTag");
		return itemDesc;
	}

	itemDesc = iter->second;
	return itemDesc;
}

_float3 CItemDB::GetItemSlotColor(CItem::ITEM_GRADE eItemGrade)
{
	_float3 vColor = { 0.f, 0.f, 0.f };
	switch (eItemGrade)
	{
	case Client::CItem::NORMAL:
		vColor = SLOT_COLOR; //회색
		break;
	case Client::CItem::ADVANCED:
		vColor = SLOT_ADVANCED_COLOR; //초록
		break;
	case Client::CItem::RARE:
		vColor = SLOT_RARE_COLOR; //파랑
		break;
	case Client::CItem::UNIQUE:
		vColor = SLOT_UNIQUE_COLOR; //보라
		break;
	case Client::CItem::LEGEND:
		vColor = SLOT_LEGEND_COLOR; //노랑
		break;
	default:
		vColor = { 1.f, 1.f, 1.f };
		break;
	}

	return vColor;
}

_float3 CItemDB::GetItemColor(CItem::ITEM_GRADE eItemGrade)
{
	// 좀 더 어두움
	//case Client::CItem::NORMAL:
	//	vColor = { 129.f / 255.f, 137.f / 255.f, 143.f / 255.f };
	//	break;
	//case Client::CItem::ADVANCED:
	//	vColor = { 110.f / 255.f, 144.f / 255.f, 80.f / 255.f };
	//	break;
	//case Client::CItem::RARE:
	//	vColor = { 199.f / 255.f, 176.f / 255.f, 80.f / 255.f };
	//	break;
	//case Client::CItem::UNIQUE:
	//	vColor = { 112.f / 255.f, 80.f / 255.f, 144.f / 255.f };

	_float3 vColor = { 0.f, 0.f, 0.f };
	switch (eItemGrade)
	{
	case Client::CItem::NORMAL:
		vColor = { 255.f / 255.f, 255.f / 255.f, 255.f / 255.f }; //회색
		break;
	case Client::CItem::ADVANCED:
		vColor = { 50.f / 255.f, 230.f / 255.f, 80.f / 255.f }; //초록
		break;
	case Client::CItem::RARE:
		vColor = { 50.f / 255.f, 150.f / 255.f, 255.f / 255.f }; //파랑
		break;
	case Client::CItem::UNIQUE:
		vColor = { 210.f / 255.f, 110.f / 255.f, 255.f / 255.f }; //보라
		break;
	case Client::CItem::LEGEND:
		vColor = { 250.f / 255.f, 255.f / 255.f, 110.f / 255.f }; //노랑
		break;
	default:
		vColor = { 1.f, 1.f, 1.f };
		break;
	}

	return vColor;
}

_uint CItemDB::ComputeWeaponDamage(CItem::ITEM_DESC tagItemDesc)
{
	// 강화시 공격력 10%씩 증가
	assert(tagItemDesc.eItemType == CItem::ITEN_WEAPON);
	assert(tagItemDesc.iData[2] <= 5);

	return tagItemDesc.iData[0] + _uint((tagItemDesc.iData[0] * 0.1f) * tagItemDesc.iData[2]);
}

_uint CItemDB::ComputeWeaponCriticalRate(CItem::ITEM_DESC tagItemDesc)
{
	// 강화시 치명타 확률 1%씩 증가
	assert(tagItemDesc.eItemType == CItem::ITEN_WEAPON);
	assert(tagItemDesc.iData[2] <= 5);

	return tagItemDesc.iData[1] + tagItemDesc.iData[2];
}

void CItemDB::Free()
{
}