#pragma once

enum SOUND_VOLUME
{
	CUSTOM_VOLUME,
	MIN_VOLUME,
	DEFAULT_VOLUME,
	MAX_VOLUME,
};

namespace Engine
{
	static const unsigned int g_iShadowWidth = 12800;
	static const unsigned int g_iShadowHeight = 7200;

	enum MOUSE_KEYSTATE { DIMK_LB, DIMK_RB, DIMK_WHEEL, DIMK_END };
	enum MOUSE_MOVESTATE { DIMM_X, DIMM_Y, DIMM_WHEEL, DIMM_END };
	enum KEY_STATE { HOLD, TAP, AWAY, NONE };

	enum BUFFER_TYPE { BUFFER_TEX, BUFFER_MESH, BUFFER_END };

	enum EFFECT_TYPE { ID_MESH, ID_PARTICLE, TYPE_RECT, EFFECT_TYPE_END };

	enum Figure { ID_RHOMBUS, ID_RECT, ID_TRIANGLE, ID_END };

	enum PARTICLE_PASS { PASS_ALPHABLEND, PASS_COLOR_T0_ALPHA, PASS_END };

}

namespace COMPONENT
{
	enum
	{
		RENDERER = 10000,
		TRANSFORM,
		TEXTURE,
		SHADER,
		VIBUFFER,
		VIBUFFER_RECT,
		VIBUIFFER_RECT_NOR,
		VIBUIFFER_SSD_BOX,
		VIBUFFER_CUBE,
		VIBUFFER_TRIANGLE,
		VIBUFFER_FLOOR_TERRAIN,
		VIBUFFER_TERRAIN,
		VIBUFFER_CHARACTERSELECT_TERRAIN,
		MODEL,
		MODEL_ANIM,
		SPHERE,
		OBB,
		CARCULATOR,
		NAVIGATION
	};
}