#pragma once

enum LEVEL_ID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_CITY, LEVEL_FOREST, LEVEL_CROWN, LEVEL_TEST, LEVEL_ANIMTOOL, LEVEL_END };

enum COLLISION_LAYER { COLL_BASE, COLL_MOVE, COLL_PLAYERATTACK, COLL_MONSTERATTACK, COLL_INTERACTION , COLL_RIM_INTERACTION , COLL_END };

enum SOUND_CHANNEL
{
	SOUND_BGM,
	SOUND_VFX,

	// 환경 효과음
	SOUND_AMBIENCE1,
	SOUND_AMBIENCE2,
	
	// 여기까지 SFX
	SOUND_PLAYER_SWING,			// SWING : 공격 액션 효과음	
	SOUND_PLAYER_HIT,			// HIT : 피격
	SOUND_PLAYER_MISSILE,		// MISSILE : 투사체 
	SOUND_PLAYER_TEMP,			// TEMP : 기타
	SOUND_MONSTER1_SWING,		
	SOUND_MONSTER1_HIT,
	SOUND_MONSTER1_MISSILE,
	SOUND_MONSTER1_TEMP,
	SOUND_MONSTER2_SWING,
	SOUND_MONSTER2_HIT,
	SOUND_MONSTER2_MISSILE,
	SOUND_MONSTER2_TEMP,
	SOUND_ECHO_SWING,
	SOUND_ECHO_MISSILE,
	SOUND_ECHO_TEMP,

	// VOICE
	SOUND_PLAYER_VOICE,
	SOUND_MONSTER1_VOICE,
	SOUND_MONSTER2_VOICE,
	SOUND_NPC_VOICE,

	// BUTTON : 버튼 조작 시 발생하는 사운드
	// FFEDBACK : 조작에 대해 반응하면서 나오는 사운드 ex) 팝업창 열리는 소리
	// TEMP : 기타
	SOUND_UI_BUTTON,
	SOUND_UI_FEEDBACK,
	SOUND_UI_TEMP,

	SOUND_END
};

// 원소 속성
enum ELEMENT
{
	ELMT_NONE,		// 무속성	- 하얀색(대미지 폰트 색상)
	ELMT_SPECTRA,	// 빛		- 노란색
	ELMT_HAVOC,		// 어둠		- 자주색
	ELMT_AERO,		// 바람		- 연두색
	ELMT_FUSION,	// 불		- 주황색
	ELMT_GLACIO,	// 얼음		- 하늘색
	ELMT_CONDUCTO,	// 번개		- 보라색
	ELMT_END
};