#pragma once

namespace SMODEL
{
	// StaticModel
	enum
	{
		SMD_TEST = 3000,

		SMD_SWORD_1_MAIN,
		SMD_SWORD_1_SUB,
		SMD_SWORD_2_MAIN,
		SMD_SWORD_2_SUB,
		SMD_SWORD_3_MAIN,
		SMD_SWORD_3_SUB,
		SMD_SWORD_4_MAIN,
		SMD_SWORD_4_SUB,
		SMD_SWORD_5_MAIN,
		SMD_SWORD_5_SUB,

		SMD_GUN_1,
		SMD_GUN_2,
		SMD_GUN_3,
		SMD_GUN_4,
		SMD_GUN_5,

		SMD_HULU_1,
		SMD_HULU_2,
		SMD_HULU_3,

		SMD_SKY,
		SMD_SKY_LOBBY,

		SMD_FLOATING_ROCK_01,
		SMD_FLOATING_ROCK_01_LOD,

		SMD_LOBBY_ROCK_0,
		SMD_LOBBY_ROCK_1,
		SMD_LOBBY_ROCK_2,
		SMD_LOBBY_ROCK_3,
		SMD_LOBBY_ROCK_4,
		SMD_LOBBY_ROCK_5,
		SMD_LOBBY_ROCK_6,

		SMD_SIMPLE_BOX,
		SMD_STANDARD_BOX,
		SMD_EXPANDED_BOX,

		INTERACTION_ROCK = 20000,
		INTERACTION_ROCK_02,

		// 장식
		SMD_CIT_BUI_0 = 51000,
		SMD_CIT_BUI_1,
		SMD_CIT_BUI_2,
		SMD_CIT_BUI_3,
		SMD_CIT_BUI_4,
		SMD_CIT_BUI_5,
		SMD_CIT_BUI_6,
		SMD_CIT_BUI_7,
		SMD_CIT_BUI_8,
		SMD_CIT_BUI_9,
		SMD_CIT_BUI_10,
		SMD_CIT_BUI_11,
		SMD_CIT_BUI_12,
		SMD_CIT_BUI_13,
		SMD_CIT_BUI_14,
		SMD_CIT_BUI_15,
		SMD_CIT_BUI_16,
		SMD_CIT_BUI_17,

		SMD_CIT_ELE_0,
		SMD_CIT_RAI_0,

		// 바닥
		SMD_CIT_GRO_0,

		SMD_CIT_STA_0,
		SMD_CIT_STA_1,

		// 상호작용
		SMD_CIT_DES_0,
		SMD_CIT_STO_0,

		// 다리
		SMD_CIT_BRI_0,
		SMD_CIT_BRI_1,
		SMD_CIT_BRI_2,
		SMD_CIT_BRI_3,

		SMD_END
	};
}

namespace DMODEL
{
	// AnimModel
	enum
	{
		DMD_PLAYERGIRL_MODEL = 4000,
		DMD_PLAYERGIRL_ANIMSET_BASE,
		DMD_PLAYERGIRL_ANIMSET_RIBBON,
		DMD_PLAYERGIRL_UI_BASE,
		DMD_PLAYERGIRL_UI_RIBBON,
		DMD_PLAYERGIRL_ACT,

		DMD_LOBBY_CHARACTER_MODEL,
		DMD_LOBBY_MALE_MODEL,
		DMD_LOBBY_MALE_ANIMSET,

		DMD_YANGYANG_MODEL,
		DMD_YANGYANG_ANIMSET_BASE,
		DMD_YANGYANG_ANIMSET_RIBBON,
		DMD_YANGYANG_UI_BASE,
		DMD_YANGYANG_UI_RIBBON,

		DMD_CHIXIA_MODEL,
		DMD_CHIXIA_ANIMSET_BASE,
		DMD_CHIXIA_ANIMSET_RIBBON,
		DMD_CHIXIA_UI_BASE,
		DMD_CHIXIA_UI_RIBBON,

		DMD_MONSTER_CROWNLESS_P1,
		DMD_MONSTER_CROWNLESS_P2,
		DMD_MONSTER_CROWNLESS_P3,
		DMD_MONSTER_CROWNLESS_ACT,
		DMD_MONSTER_INFERNORIDER,

		DMD_MONSTER_HKACACA,
		DMD_MONSTER_GAZIZI,
		DMD_MONSTER_AWUKAKA,
		DMD_MONSTER_FHUXIUXIU,

		DMD_MONSTER_ANJIN,
		DMD_MONSTER_HUOJIN,
		DMD_MONSTER_FENGLIE,
		DMD_MONSTER_BINGLIE,
		DMD_MONSTER_LEILIE,

		DMD_MONSTER_BINLANG_01,
		DMD_MONSTER_BINLANG_02,
		DMD_MONSTER_BINLANG_ELITE,

		DMD_MONSTER_LEIFA,
		DMD_MONSTER_QUNJING,

		DMD_ECHO_GAZIZI,
		DMD_ECHO_AWUKAKA,
		DMD_ECHO_FHUXIUXIU,
		DMD_ECHO_ANJIN,
		DMD_ECHO_HUOJIN,
		DMD_ECHO_FENGLIE,
		DMD_ECHO_BINGLIE,
		DMD_ECHO_LEILIE,
		DMD_ECHO_QUNJING,
		DMD_ECHO_CROWNLESS_P3,

		DMD_UI_ROVER,
		DMD_UI_ROVER_RIBBON,

		DMD_UI_YANGYANG,
		DMD_UI_YANGYANG_RIBBON,

		DMD_UI_CHIXIA,
		DMD_UI_CHIXIA_RIBBON,

		DMD_SHOP_GIRL,
		DMD_COOK_GIRL,
		DMD_DELIVER,

		DMD_END
	};
}