#pragma once

// Object
namespace OBJECT
{
	enum
	{
		INTRO = 5000,
		BACKGROUND,

		STATIC_CHARACTER_STATE,
		STATIC_CAM_MOVEMENT,
		ACTION_CAM_BANGSUN,

		TERRAIN,
		FLOOR,
		CHARACTERSELECT_TERRAIN,

		LOBBY_ROCK,
		MAP_OBJECT,
		CITY_OBJECT,

		INTRO_CAMERA,
		DYNAMIC_CAMERA,
		PLAYER_CAMERA,

		LOBBY_CHARACTER_LEFT,
		LOBBY_CHARACTER_RIGHT,

		UI_INTERACTION,
		UI_ACQUIRE,
		ACQUIRE_SYSTEM,
		INVENTORY,

		PLAYER_PLAYERGIRL,
		PLAYER_YANGYANG,

		SANDBAG,

		MONSTER_GAZIZI,
		MONSTER_ANJIN,
		MONSTER_AWUKAKA,

		MONSTER_CROWNLESS_P1,
		MONSTER_CROWNLESS_P2,
		MONSTER_CROWNLESS_P3,

		PARTS_SWORD_0_SWORD,
		PARTS_SWORD_0_SCABBARD,
		PARTS_GUN_0,

		PARTS_HULU_0,
		PARTS_HULU_1,
		PARTS_HULU_2,
		
		SKY,
		SKY_LOBBY,
		FLOATING_STONE,

		UI,
		MOUSE,
		UIMINIMAP,
		UITAPT,
		UIMONSTER,
		UITIP,
		UIMERCHANTMEN,

		INTERACTION,
		CHEST_SIMPLE,
		CHEST_STANDARD,
		CHEST_EXPANDED,

		UI_TERMINAL,
		UI_TERMINAL_RESONATOR,

		ITEM,

		MISSILE,
		MISSILE_CONSTANT,
		MISSILE_ROTAROUND,

		UICharacter,

		// AnimTool 전용 오브젝트
		TESTVTF_BEGIN = 900000,
		TESTVTF_PLAYERGIRL = 900000,
		TESTVTF_PLAYERGIRL_UI,
		TESTVTF_YANGYANG,
		TESTVTF_YANGYANG_UI,
		TESTVTF_CHIXIA,
		TESTVTF_CHIXIA_UI,
		TESTVTF_END,

		TESTGENERIC_BEGIN = 910000,
		TESTGENERIC_GAZIZI = 910000,
		TESTGENERIC_AWUKAKA,
		TESTGENERIC_HKACACA,
		TESTGENERIC_FHUXIUXIU,
		TESTGENERIC_ANJIN,
		TESTGENERIC_HUOJIN,
		TESTGENERIC_BINGLIE,
		TESTGENERIC_FENGLIE,
		TESTGENERIC_LEILIE,
		TESTGENERIC_LEIFA,
		TESTGENERIC_QUNJING,
		TESTGENERIC_BINLANG_01,
		TESTGENERIC_BINLANG_02,
		TESTGENERIC_BINLANG_ELITE,

		TESTGENERIC_CROWNLESS_P1,
		TESTGENERIC_CROWNLESS_P2,
		TESTGENERIC_CROWNLESS_P3,
		TESTGENERIC_INFERNORIDER,

		TESTGENERIC_END,
	};
}

