#pragma once

enum LEVEL_ID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_ANIMTOOL, LEVEL_END };

enum COLLISION_LAYER { COLL_BASE, COLL_MOVE, COLL_ATTACKNHIT, COLL_END };

enum SOUND_CHANNEL
{
	BGM,
	VFX
};