#pragma once

enum LEVEL_ID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_CITY, LEVEL_FOREST, LEVEL_TEST, LEVEL_ANIMTOOL, LEVEL_END };

enum COLLISION_LAYER { COLL_BASE, COLL_MOVE, COLL_PLAYERATTACK, COLL_MONSTERATTACK, COLL_END };

enum SOUND_CHANNEL
{
	BGM,
	VFX
};

// 원소 속성
enum ELEMENT
{
	ELMT_NONE,		// 무속성	- 하얀색(대미지 폰트 색상)
	ELMT_SPECTRA,	// 빛		- 노란색
	ELMT_HAVOC,		// 어둠		- 자주색
	ELMT_AERO,		// 바람		- 연두색
	ELMT_FUSION,	// 불		- 주황색
	ELMT_GLACIO,	// 얼음		- 하늘색
	ELMT_CONDUCTO,	// 번개		- 보라색
	ELMT_END
};